spring:
  application:
    name: ms-routes
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/routes_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver

server:
  port: 8085

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

jwt:
  secret: ${JWT_SECRET:}

internal:
  api-key: ${INTERNAL_API_KEY:}

app:
  ms-vehicles:
    url: ${MS_VEHICLES_URL:http://localhost:8082}
  ms-drivers:
    url: ${MS_DRIVERS_URL:http://localhost:8083}

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
      ms-vehicles:
        connectTimeout: 2000
        readTimeout: 5000
      ms-drivers:
        connectTimeout: 2000
        readTimeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      msVehicles:
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 1
      msDrivers:
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 1