spring:
  application:
    name: ms-routes
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/routes_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
  cloud:
    openfeign:
      ok

server:
  port: 8085

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

jwt:
  secret: ${JWT_SECRET}

internal:
  api-key: ${INTERNAL_API_KEY}

clients:
  vehicle-service: ${VEHICLE_SERVICE_URL:http://ms-vehicles:8082}
  driver-service: ${DRIVER_SERVICE_URL:http://ms-drivers:8083}
