spring:
  application:
    name: ms-auth
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    es.bytescolab.msauth: INFO
    org.springframework.security: WARN

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

internal:
  api-key: ${INTERNAL_API_KEY}

demo:
  admin-password: ${DEMO_ADMIN_PASSWORD}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
