spring:
  application:
    name: ms-alerts
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/alerts_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver

server:
  port: 8088

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

jwt:
  secret: ${JWT_SECRET}

internal:
  api-key: ${INTERNAL_API_KEY}
